title: advent-of-code
tagline: A brand new course on Learning Lab
description: asdasd
template:
  repo: advent-of-code-template
  name: advent-of-code
  description: a christmas adventure!
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: Second Step
    actions:
      - type: createPullRequestComment
        body: pr-comment.md
        file: some-file.js
        position: '1'
    description: 'second '
    event: pull_request.opened
